### ISSUE TITLE
CircleCI integration is broken

### ISSUE THREAD

**Issue by tobiasweibel** [codacy/codacy-stylelint#8]
See e.g. PRs 
* https://github.com/codacy/codacy-stylelint/pull/7 (no status for ci/circleci:build)
* https://github.com/codacy/codacy-stylelint/pull/5 (link to invalid ci/circleci:build)

**Comment by IGFCoimbra** [comment]
Hi @tobiasweibel 

I'm very sorry for the delay in getting back to you.

The Open Source community is an integral part of who we are and we are putting resources in place to make sure all past and future user contributions are reviewed in a timely manner moving forward. I have opened an internal ticket regarding this issue and it is already in our developers' queue. I will let you know as soon as we have any feedback on this.

Regards,
Ivo

**Comment by lolgab** [comment]
CircleCI build has been fixed in #9. Now it runs correctly on new PRs.
Thank you for opening the issue report.
